# Generated by Django 4.1.5 on 2023-02-28 15:27

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='category/')),
            ],
        ),
        migrations.CreateModel(
            name='Programmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('name', models.CharField(max_length=255, verbose_name='Full Name')),
                ('bio', models.TextField(blank=True, max_length=500, null=True)),
                ('gUrl', models.CharField(blank=True, max_length=255, null=True, verbose_name='Github')),
                ('fUrl', models.CharField(blank=True, max_length=255, null=True, verbose_name='Facebook')),
                ('tUrl', models.CharField(blank=True, max_length=255, null=True, verbose_name='Twitter')),
                ('iUrl', models.CharField(blank=True, max_length=255, null=True, verbose_name='Instagram')),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('level', models.CharField(blank=True, max_length=255, null=True, verbose_name='Level')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dev', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('title', models.TextField()),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', primary_key=True, serialize=False)),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Code-Content')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(default='uncategorize', on_delete=django.db.models.deletion.SET_DEFAULT, to='api.category')),
                ('dev', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.programmer')),
            ],
        ),
    ]
