# Generated by Django 4.1.5 on 2023-03-06 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.ImageField(blank=True, default='lama', null=True, upload_to='icon/'),
        ),
    ]
