# Generated by Django 4.1.5 on 2023-03-08 03:17

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_category_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='code',
            field=models.TextField(default='lama', verbose_name='Code Snippet'),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Description/Steps'),
        ),
    ]
